database:
  host: localhost
  port: 5432
  user: postgres
  password: yourpassword
  database: docfusiondb
  max_connections: 10
  min_connections: 1
  connection_timeout: 30
  idle_timeout: 600

server:
  host: 0.0.0.0
  port: 8080
  workers: 4

logging:
  level: info
  format: json
  file: null
